src/grammar.pest
Closes #9
Quick fix to include `fn` for function parsing
=> Updating grammar to respect `fn` keyword

src/grammar.pest, src/parser.rs
Adds handling so that `;` can be used to pass multiple commands to the REPL.
**Unlike R**, this does not evaluate each expression in sequence, it instead parses to an AST that is equivalent to a `{` block. This means that the call stack will look slightly different when compared to R. 
This only has an impact at the top level, within any subsequent call, any `;` would be interpreted as part of a block anyways so there shouldn't be a difference. 
I'm undecided on whether this is a feature or a bug. I sort of like that this reduces the problem space a bit, consolidating on a consensus form for representing REPL input, but it would break some compatibility.
=> Adding semicolon parsing; parses to { block

Cargo.lock, Cargo.toml, src/error.rs, src/grammar.pest, src/lang.rs, src/parser.rs, src/r_builtins/builtins.rs, src/r_builtins/callstack.rs, src/r_builtins/mod.rs, src/r_builtins/paste.rs, src/r_repl/highlight.rs, src/r_repl/prompt.rs, src/r_repl/repl.rs, src/utils.rs
- Adds a `CallStack` structure which implements the `Context` trait, adding frames (with new local function body environments) when calls are made
- Adds a `callstack()` primitive - I couldn't bring myself to name it `"sys.calls"` (what is `sys` anyways?), but that's effectively what it is.
- Filling in a few gaps for displaying objects, namely for closures and environments for debugging
And it looks something like this:
```r
> x <- function(...) paste(...)
> y <- function(...) x(...)
> z <- function(...) y(...)
> z('a', c('b', 'c'), collapse = 3)
```
_currently this is the only error that surfaces a traceback automatically, just to test out the feature_
- Bring some dependencies up-to-date
- Allow parser to parse single expressions without adding extra `{ ... }` wrapping primitive
=> Adds call stack evaluation context, primitive `callstack()`

src/ast.rs, src/callable/core.rs, src/callable/dyncompare.rs, src/callable/keywords.rs, src/callable/mod.rs, src/callable/operators.rs, src/callable/primitive/c.rs, src/callable/primitive/callstack.rs, src/callable/primitive/list.rs, src/callable/primitive/paste.rs, src/callable/primitive/q.rs, src/error.rs, src/lang.rs, src/lib.rs, src/repl/repl.rs, src/utils.rs, src/vector/vectors.rs
* Derives `PartialEq` for all lang and ast objects
* Had to do some nasty up-and-back-downcasting magic to implement `PartialEq` for `Primitive`s, thankfully covered in "Learning Rust" and was pretty easy to adapt.
* Added a `assert_r_eq!` macro that will parse and evaluate (most) R code and compare the output of the test case and expectation
=> Implementing PartialEq; adding assert_r_eq! macro

src/callable/operators.rs, src/grammar.pest, src/parser.rs
As a bonus, I added a tertiary colon operator as well (`1:2:10`).
Also fixed a longstanding bug with numeric parsing where `.3` would get interpreted as a variable name and not a number.
=> Adding colon operator

demo/index.html, src/callable/operators.rs, src/callable/primitive/c.rs, src/callable/primitive/paste.rs, src/lang.rs, src/lib.rs, src/utils.rs, src/vector/coercion.rs, src/vector/iterators.rs, src/vector/mod.rs, src/vector/rep.rs, src/vector/subset.rs, src/vector/subsets.rs, src/vector/vectors.rs
After a few separate attempts to get #46 working, I realized that the ethos of that refactor was leading toward a pretty wild overhaul that I wasn't quite prepared for. To keep things a bit more manageable, I split off just the part that felt most pressing to me - being able to assign by mutable slice. 
I'm really happy with how that part came together. The subsetting works really nicely and the list of R objects just dispatches to the right handler for internal equivalents to most top level actions (get-by-index, assign-by-index, call). 
In the process, I learned a lot about how to write generic code. Writing the vector representations as type-generic felt very comfortable, but it means that at _some point_ we either have to have R know which types are in each vec, or we have to make the …
=> Mutable vector access, "alt-reps" and subestting

README.md, src/CHANGELOG.md, src/callable/builtins.rs, src/lang.rs, src/object/list.rs, src/object/vector/subset.rs, src/object/vector/subsets.rs, src/repl/release.rs
* Mutating assignment implemented for `List`s, including by named index.
```r
x <- list(a = 1, b = 2, c = 3, d = 4, e = 5)
x[2:3][[1]] <- 200
x[1:4][c("d", "c")] <- 1000
x
```
* `List`s were reworked to use a `HashMap` of named values, allowing for
more immediate access to named values without repeated traversals of a 
vector of pairs.
=> Rewriting `List` internals and adding named subsets

src/CHANGELOG.md, src/callable/operators.rs, src/grammar.pest, src/lang.rs, src/object/list.rs, src/object/vector/subsets.rs
* Adds destructuring assignment `(x, y) <- (a = 1, b = 2)`. I hope to expand this in the future for arbitrarily nested built-in data type matching, but for now it only works with named and unnamed symbols. 
Minor changes
* Updated pairs syntax (used for vectors and lists) to disallow more than one trailing comma
* Disallow `.`s in symbols! After many years of R this still feels weird and is used for both names and meaningful S3 method notation.
* Trying to index into a list with a name it does not contain no longer erroneously returns the first element.
=> Destructuring assignment

.github/workflows/deploy-demo.yml, .github/workflows/release.yml, .github/workflows/test.yml, Cargo.toml, src/bin.rs, src/lang.rs, src/object/vector/rep.rs, src/repl/release.rs
* Adding testing and linting jobs
=> Updating actions

src/grammar.pest, src/parser.rs
Closes #68 
This should allow any whitespace between a negative sign and the rest of an expression, and non-newline whitespace between an expression and postfix operators (`(`, `[[`, `[`)
For example, this will now parse `- 1` and `q ()`
@sebffischer tagging for interest in case you'd like to learn a bit about the parser
=> Allow whitespace between prefix/postfix operators

src/grammar.pest
This just does for integers, what has already been done for numbers here https://github.com/dgkf/R/pull/70
=> fix: remove never matching "-" prefix from integer rule

src/CHANGELOG.md, src/grammar/grammar.pest, src/object/ast.rs, src/parser/core.rs
This allows for better readability, especially of large numbers.
Solves #97
=> feat(parser): Support "_" to separate digits

src/lang.rs
Closes #107
Quick fix, forcing finalizing of tail call evaluation when assigning. Just an overlooked part of the evaluation scheme that didn't get updated when introducing tail calls.
=> Fix: assigning from tail finalizes before assignment

src/CHANGELOG.md, src/context/core.rs, src/repl/core.rs, src/session.rs
Closes #115
Binary operator expressions are now "finalized", meaning that tail calls get coerced into returns instead of awaiting lazy evaluation. 
This does mean that when the binary operator expression is the "tail" it will no longer apply tail call optimization. This is a preferred behavior for the immediate future and may prove to be the preferred style long term.
```r
$ r --experiments=tail-calls
> f <- fn(n) if (n > 0) 1 + f(n - 1) else n
> f(100)
> f(1000)
```
=> fix: Addressing hanging tail calls short-circuiting binary ops

src/CHANGELOG.md, src/grammar/grammar.pest, src/lang.rs
Partially solves https://github.com/dgkf/R/issues/101
=> feat: allow assignment using =

demo/assets/prompt/src.js, demo/index.html, src/callable/primitive/print.rs, src/object/environment.rs, src/repl/core.rs, src/repl/headless.rs, src/repl/highlight.rs, src/repl/validator.rs, src/session.rs
Adds `Session.output` field, defining how output should be displayed. Must implement `std::fmt::Write`.
For now it only has two variants - either stdout or a callback. The callback allows for a JavaScript function to be passed as a callback to append output as it is printed.
=> Adding callback output mode, allowing printing in wasm

src/callable/builtins.rs, src/callable/core.rs, src/callable/primitive/environment.rs, src/callable/primitive/names.rs, src/callable/primitive/parent.rs, src/context/core.rs, src/lang.rs, src/object/core.rs, src/object/environment.rs
Closes #122
Fix: Saves result of forcing promise back into environment, instead of re-evaluating it every time.
Chore: Renames `Closure` to `Promise`. Maybe eventually there will be a need for both, but for now I think `Promise` is a better indication of what this represents. A `Closure` might be better represented by a function anyways (I think internally R refers to its functions as "closures" anyways since they always capture their environments).
=> Fix: promise evaluation

src/CHANGELOG.md, src/callable/builtins.rs, src/callable/core.rs, src/callable/primitive/environment.rs, src/callable/primitive/mod.rs, src/callable/primitive/names.rs, src/callable/primitive/parent.rs, src/callable/primitive/substitute.rs, src/context/core.rs, src/lang.rs, src/object/core.rs, src/object/environment.rs
- Reworks what was `Closure` (this was probably misnamed to begin with) as `Promise` and adopts R's style of promise which retains its originating expression even after being forced. 
- Adds `substitute()`
=> feat: add primitive substitute

r_derive/src/lib.rs, src/cli.rs, src/parser/core.rs, src/parser/localization/core.rs, src/repl/core.rs, src/repl/headless.rs, src/repl/highlight.rs, src/repl/release.rs, src/repl/validator.rs, src/session.rs
When I was adding the localization I accidentally forgot to pass experiments down to the repl validator and highlighter. This had the odd result of breaking in the terminal, but not in wasm where we skip the reedline repl and use the internals directly to build our own repl. 
Now both repls should allow `--experiments` again
=> fix: re-enable experiment flags

r_derive/src/lib.rs, src/callable/core.rs, src/callable/keywords.rs, src/callable/primitive/substitute.rs, src/grammar/grammar.pest, src/object/ast.rs, src/parser/core.rs
This one ended up exposing a few other bugs related to handling of parenthesis. 
Before they weren't actually part of the syntax tree. They just existed through the structure of the tree itself - implicit to the interpreter but non-obvious when printed. Anything that looked like it printed reasonably before was just little tricks I had shoved in to make it look reasonable along the way.
Now parenthesis have their own symbol so this should be much more rigorously handled in the future.
I also spent a little time cleaning up `substitute()`, which does some "automatic" parentheses insertion when operator precedence might affect behaviors, similar to R.
=> fix: parenthesis now appear in printed quote objects

src/lang.rs
Promises were evaluating, but not _finalizing_ their expressions, which can result in un-evaluated tail-calls in the case of nested promises.
Now they are also _finalized_
Closes #141
=> fix: nested promises force and finalize any lingering tails

r_derive/src/lib.rs, src/callable/core.rs, src/callable/primitive/names.rs, src/error.rs, src/grammar/grammar.pest, src/lang.rs, src/parser/core.rs, src/parser/localization/core.rs, src/repl/core.rs, src/repl/headless.rs, src/utils.rs
Closes #133; Inspired by the discussion in #133
```r
f <- fn(...) list(...)
f(1, 2, 3)
f <- fn(...) .
f(1, 2, 3)
```
```r
f <- fn(...) list(...)
f(1, 2, 3)
f <- fn(...) .
f(1, 2, 3)
```
* Treats `...` as a "rest" argument, similar to any other "rest" argument using the "more" operator (`..`). When the `rest-args` experiment is enabled, `...` gets parsed as a _named_ ellipsis argument with the name `.`.
* Adds `parse`, and `parse_and_eval` as methods of `CallStack` to make it easier to write tests that make use of experiments
* Cleans up some legacy uses of `session.local.parse_input_with` and replaces with `parser_config.parse_input`
* Fixes feature disabled error message to display correct command to enabled features.
* `CallStack::default()` now defaults to a global environment with …
=> Feature: Generalize ellipsis as a `..rest` argument (when `rest-args` enabled)

src/object/environment.rs
The builtin environment's functions contain the builtin environment
Resolves Issue #147
=> fix: don't recurse in debug implementation for environment

src/lang.rs
Implement `Obj.get` for `List`, necessary for `<list>[<indices>] <- <list>` to function properly.
=> fix: assignment of list to list subset

src/callable/operators.rs, src/context/core.rs, src/parser/core.rs
This might be a change we revert at some point if we ever want to return lazy list elements, but for now it has the intended behavior.
Like the vector syntax `[1, 2, 3]`, we now have a list syntax primitive `(1, 2, 3)` which knows to evaluate similar to `PrimitiveList`.
=> fix: lists parsed as call to primitive instead of Expr::List

r_derive/src/lib.rs, src/callable/builtins.rs, src/callable/operators.rs, src/grammar/grammar.pest, src/lang.rs, src/object/vector/core.rs, src/object/vector/rep.rs, src/object/vector/reptype.rs, src/parser/core.rs
Somehow missed the implementation of `!`. Now added. Also updated all the internal naming conventions to use "not" instead of what was mistakenly called "negate" :sweat_smile:
=> fix: implement missing negation operator

src/callable/primitive/substitute.rs, src/lang.rs
Closes #136
Resolving a bug where accessing a promise mutably didn't prompt the actual value of the promise to be updated. Now promises, when accessed mutably on the lhs of assignment, will mask themselves with their materialized value.
=> Fix: Mutating promises materializes value
